/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package http.server.gradle;

import java.io.File;

import com.kogaplanet.lunarlatteMarkupLanguage.Parser;
import com.kogaplanet.lunarlatteMarkupLanguage.api.TagHandler;

public class App {
	
	String response;
	
	public App() {
		TagHandler handler = new TagHandler();
    	handler.parserInit(new Parser("config.3ml"));
    	this.response = handler.call("daisy").data.get(0);
	}
    
    public static void main(String[] args) {
    	//	System.out.println(file.getAbsolutePath()); 
    	new App();
    	File file = new File("App.java"); 
    	System.out.println(new App().parserResponse());
    
    }
    
    public String parserResponse() {
		
    	return this.response;
	}
}
