/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package http.server.gradle;

import org.junit.Test;

import com.kogaplanet.lunarlatteMarkupLanguage.Parser;
import com.kogaplanet.lunarlatteMarkupLanguage.api.TagHandler;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void isParserWorking() {
    	TagHandler handler = new TagHandler();
    	handler.parserInit(new Parser("config.3ml"));
    	
    	assertNotNull("The parser is retrieving data", handler.call("daisy"));
    }
}
